/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Telas;

/**
 *
 * @author bernardo.morschheise
 */
public class TelaPrincipal extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaPrincipal.class.getName());
    private TelaInCadCliente tic;
    private TelaInCadFuncionario tif;
    private TelaInCadPedido tip;
    private TelaInCadProduto tipr;

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DskPainel = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        MenCadastro = new javax.swing.JMenu();
        MeniClientes = new javax.swing.JMenuItem();
        MeniFuncionarios = new javax.swing.JMenuItem();
        MeniProdutos = new javax.swing.JMenuItem();
        MeniPedidos = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout DskPainelLayout = new javax.swing.GroupLayout(DskPainel);
        DskPainel.setLayout(DskPainelLayout);
        DskPainelLayout.setHorizontalGroup(
            DskPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 770, Short.MAX_VALUE)
        );
        DskPainelLayout.setVerticalGroup(
            DskPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 414, Short.MAX_VALUE)
        );

        MenCadastro.setText("CADASTRO");

        MeniClientes.setText("CLIENTES");
        MeniClientes.addActionListener(this::MeniClientesActionPerformed);
        MenCadastro.add(MeniClientes);

        MeniFuncionarios.setText("FUNCIONARIOS");
        MeniFuncionarios.addActionListener(this::MeniFuncionariosActionPerformed);
        MenCadastro.add(MeniFuncionarios);

        MeniProdutos.setText("PRODUTOS");
        MeniProdutos.addActionListener(this::MeniProdutosActionPerformed);
        MenCadastro.add(MeniProdutos);

        MeniPedidos.setText("PEDIDOS");
        MeniPedidos.addActionListener(this::MeniPedidosActionPerformed);
        MenCadastro.add(MeniPedidos);

        jMenuBar1.add(MenCadastro);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DskPainel)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DskPainel)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MeniClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MeniClientesActionPerformed

        if (tic == null || tic.isClosed()) {
            tic = new TelaInCadCliente();
            tic.setVisible(true);
            DskPainel.add(tic);
        }

    }//GEN-LAST:event_MeniClientesActionPerformed

    private void MeniFuncionariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MeniFuncionariosActionPerformed

        if (tif == null || tif.isClosed()) {
            tif = new TelaInCadFuncionario();
            tif.setVisible(true);
            DskPainel.add(tif);
        }

    }//GEN-LAST:event_MeniFuncionariosActionPerformed

    private void MeniPedidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MeniPedidosActionPerformed

        if (tip == null || tip.isClosed()) {
            tip = new TelaInCadPedido();
            tip.setVisible(true);
            DskPainel.add(tip);
        }

    }//GEN-LAST:event_MeniPedidosActionPerformed

    private void MeniProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MeniProdutosActionPerformed

        if (tipr == null || tipr.isClosed()) {
            tipr = new TelaInCadProduto();
            tipr.setVisible(true);
            DskPainel.add(tipr);
        }

    }//GEN-LAST:event_MeniProdutosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TelaPrincipal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane DskPainel;
    private javax.swing.JMenu MenCadastro;
    private javax.swing.JMenuItem MeniClientes;
    private javax.swing.JMenuItem MeniFuncionarios;
    private javax.swing.JMenuItem MeniPedidos;
    private javax.swing.JMenuItem MeniProdutos;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
